# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{gip}
  s.version = "0.2.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{François Beausoleil}]
  s.date = %q{2011-11-01}
  s.email = %q{francois@teksol.info}
  s.executables = [%q{gip}]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/gip",
    "features/import.feature",
    "features/step_definitions/gip_steps.rb",
    "features/support/command_line.rb",
    "features/support/env.rb",
    "gip.gemspec",
    "lib/gip.rb",
    "test/gip_test.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/francois/gip}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Gip into place: Piston without the SVN cruft}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<gip>, [">= 0"])
      s.add_runtime_dependency(%q<thor>, ["~> 0.11"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
    else
      s.add_dependency(%q<gip>, [">= 0"])
      s.add_dependency(%q<thor>, ["~> 0.11"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
    end
  else
    s.add_dependency(%q<gip>, [">= 0"])
    s.add_dependency(%q<thor>, ["~> 0.11"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
  end
end

